/*
 * This file is generated by jOOQ.
 */
package com.satya.JOOQDemo.jooq;


import com.satya.JOOQDemo.jooq.tables.Person;
import com.satya.JOOQDemo.jooq.tables.PhoneBook;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;
    public static final Index PRIMARY_KEY_B = Indexes0.PRIMARY_KEY_B;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", Person.PERSON, new OrderField[] { Person.PERSON.ID }, true);
        public static Index PRIMARY_KEY_B = Internal.createIndex("PRIMARY_KEY_B", PhoneBook.PHONE_BOOK, new OrderField[] { PhoneBook.PHONE_BOOK.ID }, true);
    }
}
