/*
 * This file is generated by jOOQ.
 */
package com.satya.JOOQDemo.jooq;


import com.satya.JOOQDemo.jooq.tables.Person;
import com.satya.JOOQDemo.jooq.tables.PhoneBook;
import com.satya.JOOQDemo.jooq.tables.records.PersonRecord;
import com.satya.JOOQDemo.jooq.tables.records.PhoneBookRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PersonRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<PhoneBookRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<PersonRecord> CONSTRAINT_8 = Internal.createUniqueKey(Person.PERSON, "CONSTRAINT_8", Person.PERSON.ID);
        public static final UniqueKey<PhoneBookRecord> CONSTRAINT_B = Internal.createUniqueKey(PhoneBook.PHONE_BOOK, "CONSTRAINT_B", PhoneBook.PHONE_BOOK.ID);
    }
}
