/*
 * This file is generated by jOOQ.
 */
package com.satya.JOOQDemo.jooq;


import com.satya.JOOQDemo.jooq.tables.Person;
import com.satya.JOOQDemo.jooq.tables.PhoneBook;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PERSON</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>PHONE_BOOK</code>.
     */
    public static final PhoneBook PHONE_BOOK = PhoneBook.PHONE_BOOK;
}
